# Generated by Django 2.0 on 2017-12-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostadmin',
            old_name='body',
            new_name='text',
        ),
    ]
