# Generated by Django 2.0 on 2017-12-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('H', 'Human')], max_length=1),
        ),
    ]
